module.exports = {
  KEY_LANGUAGE: 'language',
  KEY_TOKEN: 'token',
  PROJECT_TOKEN: 'ptoken',   //项目token
  KEY_ORG_ID: 'orgId',
  KEY_ORG_NAME: 'orgName',
  KEY_USER_ID: 'userId',
  KEY_USER_NAME: 'userName',
  KEY_PASSWORD: 'password',
  KEY_ROLE_ID: 'roleId',
  KEY_ROLE_TYPE: 'roleType',
  KEY_OPE_LIST: 'opeList',
  KEY_IS_LDAP: 'isLdap',
  KEY_DOMAIN_ID: 'domainId',
  KEY_DOMAIN_NAME: 'domainName',
  KEY_REMOTE_HOST_IP: 'remoteHostIp',
  KEY_REMOTE_PORT: 'remotePort',
  KEY_REMOTE_ADDR: 'remoteAddr',
  KEY_REMOTE_USER: 'remoteUser',
  KEY_WARN_DAYS: 'warnDays',
  KEY_PROJECT_LIST: 'projectList',
  KEY_MENUCODE_LIST: 'menuCodeList',
  KEY_SERVICES:'services',
  KEY_REGIONS:"regions",
  KEY_REGION_SERVICES:"regionServices",
  KEY_SESSION_TIMEOUT:'sessionTimeout',
  KEY_IP:"ip"
};
